### ISSUE TITLE
Port to SDL 2.x

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#102]
This one is big. SDL 1 is rather deprecated and this is already causing issues on Mac OS X.

Migration guide: https://wiki.libsdl.org/MigrationGuide#SDL_1.2_to_2.0_Migration_Guide

**Comment by ScalaWilliam** [comment]
[11:17 PM] lucasgautheron: DUDE
[11:17 PM] lucasgautheron: https://github.com/assaultcube/AC/pull/143
GitHub
SDL2 port by ujmm · Pull Request #143 · assaultcube/AC


haushaus

**Comment by lucasgautheron** [comment]
:rofl:

**Comment by ScalaWilliam** [comment]
It works on macos sierra. Here's a file: https://174-47462659-gh.circle-artifacts.com/0/Users/distiller/ActionFPS-Game/source/xcode/build/Release/actionfps.dmg

It works on Linux as well.

Doesn't link on Windows after successful compilation.

Re stability, I truly have no idea. Maybe we should just push this through as a first release?

@lucasgautheron help needed to finish the windows bit.

**Comment by ScalaWilliam** [comment]
Closing issue as fulfilled by PR: #125.
