### ISSUE TITLE
One-click auth & join

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#106]
So that the initial user flow is much better. Now it's a bit confusing.

In future we might be able to direct people to random servers that are not full :-)

https://github.com/ScalaWilliam/ActionFPS/wiki/Growth,-Philosophy#new-user-flow

**Comment by lucasgautheron** [comment]
you should be able to already.
actionfps://actionfps.com:7654?id=lucas&key=...

**Comment by ScalaWilliam** [comment]
ah I thought it was broken because I couldn't use a slash after the port.
