### ISSUE TITLE
Toggle fullscreen bind

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#111]
## What?
Introduce new bind to toggle fullscreen.
```
bind W [ fullscreen (- 1 $fullscreen) ]
```

## Why?
I can't alt-tab on linux in fullscreen. I need to toggle fullscreen all the time as a result.

**Comment by ScalaWilliam** [comment]
Why 'W'

I entered that into my game and then WTF

**Comment by lucasgautheron** [comment]
Oh sorry i'm using arrows to navigate xD W is just an example. idk what to put as default.

**Comment by ScalaWilliam** [comment]
Typically F11 (though that's used for the console). Maybe F10 could be removed. We could remove demo download support from the game as a corollary as it's not necessary anyway. Would reduce any potential abuse too.

**Comment by ScalaWilliam** [comment]
This is important for Linux users, should be in here by default. So putting as medium-priority.

**Comment by gyunderscorebe** [comment]
Um, there is already `fullscreentoggle` and it's already on the bind menu, it just doesn't have a default. Do you want to add one?

**Comment by ScalaWilliam** [comment]
Yes please. Should be F11. This would replace the 'open console' key which should be F10. This would replace the download demo key which (IMO) is unnecessary as the user can type `/getdemo`. You may choose to bind it to something else though.
