### ISSUE TITLE
Remove demo download support?

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#112]
## Why?
It's an unnecessary feature, we'd like to make demos available via other means and not the server.

There's also always potential for abuse and using too much bandwidth in sending demos to clients.

**Comment by ScalaWilliam** [comment]
Inspired by https://github.com/ActionFPS/ActionFPS-Game/issues/111#issuecomment-277435204

**Comment by lucasgautheron** [comment]
Once we have developed a reliable and consistent alternative, sure.

**Comment by ScalaWilliam** [comment]
post-boning it
