### ISSUE TITLE
On install link to /installed/

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#113]
# Feature

## What?
On install link to https://actionfps.com/installed/
## Why?
So we could then redirect the user anywhere we want (release notes/Play red button/etc)

**Comment by lucasgautheron** [comment]
* https://actionfps.com/installed/ after installation
 * https://actionfps.com/uninstalled/ after uninstallation

Is that alright ?

**Comment by ScalaWilliam** [comment]
Yes thanks.
