### ISSUE TITLE
Skins, new weapons and crates, publicity

### ISSUE THREAD

**Issue by Arleyobi** [ActionFPS/ActionFPS-Game#114]

**Comment by Arleyobi** [comment]
I think that if we want to make ActionFPS improves, we have to start adding new things. 
Im sure that all of you knows video games that have payment method for skins, skins' crates, etc... I think that it would be a nice feature to add in ActionFPS, it would generate money and we would be able to start relations with YouTubers. 
At the moment, YouTube is the best way to make publicity, if we make relations with good YouTubers, we would get new players. Then, they will start buying skins, crates and we will get a bigger player base to make ActionFPS bigger and better. Then, we will be able to start making new features in the client and trying to be make a proffesional competitive escenes, cuz eSports escene its growing up atm so fast 2, thing that would help making ActionFPS bigger too.
Sorry for my english and feel free to post your opinions.

**Comment by ScalaWilliam** [comment]
In what ways would you be able to help us achieve this?

**Comment by ScalaWilliam** [comment]
Looks nice, we'll postpone currently as 'low priority', but revisit in future time.

Make sure to add more content here in the meanwhile.
