### ISSUE TITLE
RELEASE.md

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#116]
## What?
Add a RELEASE.md file with all instructions on how to make a new release.

## Why?
I am not sure what to do. And I don't want to miss any step (as few as might be)

**Comment by ScalaWilliam** [comment]
This not enough?
https://github.com/ActionFPS/ActionFPS-Game/wiki/Release

**Comment by lucasgautheron** [comment]
It is! Forgot about the wiki, sorry.

**Comment by ScalaWilliam** [comment]
Maybe could move it into main repo instead of wiki for the sake of it.
