### ISSUE TITLE
Ensure server reloads a modified users key correctly

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#118]
# Bug

## Expected behavior
Auth key works for me
## Actual behavior
Didn't work
## Steps to reproduce behavior

(won't reproduce myself rn, but you may wanna take a look if there's any broken logic somewhere)

1. Remove user from users database
2. Add user to users database with a different key
3. connect - get ** authentication failed**
4. restart - works just fine.

**Comment by lucasgautheron** [comment]
might have been because the server does not reload config/users instantly.
would be useful to have server logs

**Comment by ScalaWilliam** [comment]
itr was like a 10 min wait

**Comment by lucasgautheron** [comment]
We can make it instant
But that might cause lags if it happens too often.

**Comment by ScalaWilliam** [comment]
once a minute is fine. Are you sure there's nothing broken in the reload logic though? 🗡

**Comment by ScalaWilliam** [comment]
maybe 30s. Just thinking about how long download+install would take for a user.

**Comment by lucasgautheron** [comment]
I need to make sure config can reload if the server is empty.
Can do 20 seconds, no problem.

**Comment by lucasgautheron** [comment]
Set it down to 5 seconds. Don't think getting a few files size is that stressful ?

**Comment by lucasgautheron** [comment]
Is it fixed for you?

**Comment by ScalaWilliam** [comment]
20 secs is enough - as most players will take that much time to dl+install the game.

Thanks - I'll reopen if it happens again.
