### ISSUE TITLE
Server hitsound (/hitsound 1) should work in singleplayer

### ISSUE THREAD

**Issue by gyunderscorebe** [ActionFPS/ActionFPS-Game#127]
# Feature

## What?

When server-side hitsounds are used (`/hitsound 1`), they should work in singleplayer, i.e. when hitting bots. Currently only local hitsounds (`/hitsound 2`) work.

## Why?

In singleplayer all player hits are immediately confirmed, so there should be no difference between `/hitsound 1` and `/hitsound 2`. Having to switch to `/hitsound 2` when playing singleplayer is inconvenient.

**Comment by ScalaWilliam** [comment]
Thanks for this, I believe we're planning on removing the bot code though.

**Comment by gyunderscorebe** [comment]
@ScalaWilliam you mean that singleplayer is going to be removed? There probably should be an issue for that.

**Comment by ScalaWilliam** [comment]
Yes. I'll create one, let's see what @lucasgautheron  says.

**Comment by ScalaWilliam** [comment]
Oops no, I mean just bots removed. Singleplayer will still be necessary if you're editing maps for example.

**Comment by gyunderscorebe** [comment]
Okay, then there is no need for this.

**Comment by ScalaWilliam** [comment]
Just close after confirmed with lucas, I don't remember that conversation very well. ;)
