### ISSUE TITLE
Remove invalid vote spam detection

### ISSUE THREAD

**Issue by gyunderscorebe** [ActionFPS/ActionFPS-Game#129]
# Feature

## What?

Currently there is a system in place that counts number of invalid votes each player called and prevents players with a few invalid votes from voting further. I propose that this "abuse" detection mechanism is removed.

## Why?

It's easy to trigger the mechanism and get locked out of voting for 4-8 minutes. All you have to do is call a valid vote that didn't pass, then call three invalid votes within 4 minutes. Invalid votes are easy to call accidentally (typos in cn or map names, trying to ban when it's not allowed by configuration, etc.) and do not affect other players in any way.

For more info on how the mechanism works see assaultcube/AC#163. [Relevant code](https://github.com/ActionFPS/ActionFPS-Game/blob/34c1a5714364b4451d0f56282aeeba4b942a918d/source/src/server.cpp#L2270-L2354).

**Comment by ScalaWilliam** [comment]
Making postponed.
