### ISSUE TITLE
Not working on Windows 10 (earlier build?)

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#132]
MSVCR100.dll

![image](https://cloud.githubusercontent.com/assets/2464813/22626313/b43ac5d2-ebe5-11e6-9862-8793e5b975af.png)

**Comment by ScalaWilliam** [comment]
Problem is in launcher.exe. Running the game by itself is just fine.

**Comment by lucasgautheron** [comment]
Launcher is crucial. Need to understand that. 
http://stackoverflow.com/a/3768535/6772256 ?
