### ISSUE TITLE
associate .dmo files to actionfps on Linux

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#133]
## What?
Opening a .dmo file should launch the game and open the demo.

## Why?
 * Loading a demo from the game is quite confusing. The GUI requires it to be in a specific location and when there are two many of them they are difficult to find.
 * Loading from the command line is not user friendly
 * Should make debugging easier for us.

## How:
File associaton:
 * Windows: http://nsis.sourceforge.net/File_Association
 * Linux: register mime type with xdg-mime
 * Mac: no idea
 * parameter to pass: --loaddemo=path

**Comment by ScalaWilliam** [comment]
reasons look good.

**Comment by lucasgautheron** [comment]
There's a difficulty because AC refuses to load stuff outside of its own directory. This is done with a horrible function: https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/src/stream.cpp#L222
We should 
 * Rewrite this thing maybe.
 * Find some elegant way to specify, in each relevant function (openfile, opengzfile etc.) if we want to allow files outside AC or not.

**Comment by lucasgautheron** [comment]
xdg-mime requires a mime type for our demo files. What name should we choose for it ?
http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by ScalaWilliam** [comment]
`application/vnd.actionfps-demo+gzip`

**Comment by lucasgautheron** [comment]
should we change the extension then?

**Comment by ScalaWilliam** [comment]
To `dmo.gz`? It does make sense somehow.

Alternatively the media type doesn't have to contain the `gz` bit.

Pros of change: more descriptive
Cons of change: work 🗡 

Do you see any other reasons?

**Comment by lucasgautheron** [comment]
No. Also that's not so complicated to fix :)

**Comment by ScalaWilliam** [comment]
Do if you like 💯
