### ISSUE TITLE
Server sends wrong team IDs

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#137]
## Why this is a problem
Inconsistent data might lead to crashes.

## Expected behavior
https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/src/clients2c.cpp#L907
ds.team should always be valid (>= 0 && < TEAM_NUM)

## Actual behavior
https://github.com/ActionFPS/ActionFPS-Game/pull/136/commits/a3960203cf973bfbfe2cde4f0610ddb4f0f2f25e#diff-bf8818975d9031677247090f896b51a6R2445
(thank you @gyunderscorebe)

## Steps to reproduce behavior
Load demo https://cdn.discordapp.com/attachments/231380080591372288/277820781344456715/20170204_1434_62.210.131.155_ac_elevation_15min_CTF.dmo (#123)
I guess @gyunderscorebe also commented out the part of the code that attempts to read a user-id before that right?

**Comment by lucasgautheron** [comment]
It looks that frags, points etc. are also wrong. But not always.
```conoutf("%d %s %d %d %d %d", team, ds.name, ds.flags, ds.frags, ds.deaths, ds.points);
```
```
player w00p|Lucas disconnected
813890 w00p|Lucas 32739 -1675698536 32739 2162709
player eM|'quico disconnected
813890 w00p|Lucas 4 38 35 563
828525 eM|'quico 0 2490391 786468 223300896
player w00p|Million disconnected
813890 w00p|Lucas 4 38 35 563
828525 eM|'quico 5 40 31 572
819673 w00p|Million -131033 220470192 0 2359320
813890 w00p|Lucas 4 38 35 563
819673 w00p|Million 5 40 31 572
connected: eM|'quico
writing to file: /home/lucas/.actionfps/v1.2next/screenshots/20170205_20.03.08_ac_elevation_CTF.jpg
player w00p|Drakas disconnected
813890 w00p|Lucas 4 38 35 563
819673 w00p|Million 4 33 26 480
808465 w00p|Drakas 4 33 26 480
813890 w00p|Lucas 4 38 35 563
819673 w00p|Million 4 33 26 480
808465 w00p|Drakas 3 18 37 254
connected: eM|'quico (1)
1 minute left!
813890 w00p|Lucas 4 38 35 563
819673 w00p|Million 4 33 26 480
808465 w00p|Drakas 3 18 37 254
connected: eM|'quico (2)
player eM|'quico (0) disconnected
813890 w00p|Lucas 4 38 35 563
0 eM|'quico 4 33 26 480
819673 w00p|Million 3 18 37 254
808465 w00p|Drakas 0 2424858 1769513 223301040
0 eM|'quico 4 38 35 563
819673 w00p|Million 5 40 31 572
808465 w00p|Drakas 4 33 26 480
connected: w00p|Lucas
```

**Comment by gyunderscorebe** [comment]
@lucasgautheron I can reproduce wrong team IDs but not the other info, are you sure you are printing it after it's already filled into the `ds` structure?

**Comment by lucasgautheron** [comment]
NVM I think you're right... I added those afterwards so that must be it. Issue closed then!

**Comment by gyunderscorebe** [comment]
Why close, team IDs are still wrong

**Comment by lucasgautheron** [comment]
They are because the bug was on the server.
So fixing it won't help with the demo. The demo is wrong forever.
