### ISSUE TITLE
Remove useless server configs

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#146]
## What?
Remove the following config files and associated code:
 * config/nicknameblacklist.cfg
 * config/serverpwd.cfg
 * config/forbidden.cfg
 * maybe also config/serverblacklist.cfg

## Why?
Some of these features are rendered useless by authentication, or have always been.
Removing them means less code to maintain.

**Comment by ScalaWilliam** [comment]
LGTM.

**Comment by ScalaWilliam** [comment]
serverblacklist, not sure, why would we want to keep it?

would an iptables blacklist suffice?

**Comment by lucasgautheron** [comment]
problem with iptables is that it goes through every packet, so in case of large blacklists and high activity, it can be CPU demanding. serverblacklist, however, operates on connection.
Also we should remove serverpwd.cfg but keep one single password just for tests.

**Comment by ScalaWilliam** [comment]
That's the CPU's job, to be used :p. Even if we're at 90% it's fine, so long as not laggy.

Do you foresee any other problem?

PS we can use tcpwrapper (supports UDP) on Linux if we need banning. (it's the `/etc/deny.hosts` stuff)
https://github.com/pexip/os-tcp-wrappers/blob/master/README

I'm quite sure the blacklist is just reinventing the wheel :p
