### ISSUE TITLE
Can't switch to other windows in winwowed mode on Mac OS

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#156]
## Why this is a problem
The user has to quit the game and restart it since he can't "alt-tab" (or whatever is the mac equivalent for this)

## Steps to reproduce behavior
@ketarXVII ? Please help describe.

**Comment by ketarXVII** [comment]
well, it is clearly a problem for me. Whenever I want to do something on my computer while I am playing I must be able to do it. After testing it with more calm and time I noticed that the exact issue is that if I press F3 (a command that on Macs displays all the windows of open apps) and I try to switch to another window from the AC one the cursor is frozen.

**Comment by lucasgautheron** [comment]
Have you tried both fullscreen and windowed ?

**Comment by ketarXVII** [comment]
this can be done only if windowed. In Full screen mode there is no way to switch to anything else (nor I can minimize it). Quitting there is the only option.

**Comment by ScalaWilliam** [comment]
Sorry, nobody available to work on this issue, so postponing.
