### ISSUE TITLE
Authentication link leads to 'authentication failed' on Mac OS

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#157]
## Why this is an important problem
Can't authenticate at all. Ketar had to make a new account (id=kkz)

## Expected behavior
Clicking on the authentication link should start the game, set authentication data and connect successfully to the server.

## Actual behavior
The server rejects the connection (authentication failed)

## Steps to reproduce behavior
@ketarXVII please describe.

**Comment by ketarXVII** [comment]
I want to try that again with a new account to reproduce it and be sure I wasn't making any mistake. Isn't there a way to sign out from afps? i mean disassociate permanently a Google account from the game (so to use it again)? If not could you do that manually on the kkz account?

**Comment by ScalaWilliam** [comment]
User needs to show his `/authid` output and first three lines of `~/Library/Application\ Support/actionfps/next/config/authkey`. Sign out is not implemented, if you'd like that, create an issue in github.com/ScalaWilliam/ActionFPS/issues

**Comment by ketarXVII** [comment]
well sign out must always be a  option (see: privacy issues and related9. But it is not my goal now i just wanted to try again without having to generate a new email account just for that. So again  could you just for now do that manually on the kkz account?

**Comment by ScalaWilliam** [comment]
https://github.com/ScalaWilliam/ActionFPS/issues

**Comment by ScalaWilliam** [comment]
Cannot reproduce the problem, and nobody to work on this, postponing.
