### ISSUE TITLE
Static vs dynamic linking?

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#160]
Just noticed that somewhere you mentioned to apt-get install stuff before running the game. Can't all the libraries be statically linked like on the Windows build? Wouldn't it be easier and simpler?

**Comment by lucasgautheron** [comment]
No

**Comment by ScalaWilliam** [comment]
Why?

**Comment by lucasgautheron** [comment]
More work, not worth it.
Static libraries for static linking are not always provided e.g. on windows, and we have to compile ourselves.
Please no, there are enough issues to fix right now

**Comment by ScalaWilliam** [comment]
Thx for clarifying
