### ISSUE TITLE
Clarify how to actually run the Mac build

### ISSUE THREAD

**Issue by gitchiu** [ActionFPS/ActionFPS-Game#162]
From b85fccd3f885d58eba00045b423ab7dead761b14 by @ScalaWilliam:

It is unclear how to run it after building. @ScalaWilliam has has problems locally but doesn't understand all the Mac-specific stuff.

**Comment by jasbrake** [comment]
Do you have trouble running the client after the build?

**Comment by ScalaWilliam** [comment]
Yes, when I built locally, I'd have random errors about missing paths or something. There are 2 entry points: the ActionFPS link & opening the game directly.

However this is not top priority right now for me.

**Comment by jasbrake** [comment]
I too had build errors and warnings.. but when I mounted the DMG file and ran that app, it worked just fine. It may not be a big concern until I find something that doesn't work.

**Comment by ScalaWilliam** [comment]
Sure, just report when you face an issue.

One solution to this issue would be to explain what to do with the DMG artifact.
Currently it doesn't explain what to do with it here: https://github.com/ActionFPS/ActionFPS-Game/tree/94ddd0d5b0c6c804a39b1714c3bba816e0bd86c9#mac

**Comment by ScalaWilliam** [comment]
Another alternative is to say that the user needs to figure out himself :) & link to this issue instead.

**Comment by ScalaWilliam** [comment]
Problem fixed:
45dc206e1838807a595012045d4985be82793f63
b1de46a90a98b7f44df34619bcc10bd9b985a798
a2e7d9e6a4d5872fc0cd54dcdbb9b9ed8b8816d5

Thanks @jasbrake
