### ISSUE TITLE
Auth doesn't work on Windows 10 for a user

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#174]
Needs someone experienced to look at this.

**Comment by ScalaWilliam** [comment]
He also reports this -> https://github.com/assaultcube/AC/commit/dae7773d68ab678e8679a667b7891451b6b1b838

**Comment by BrutalSystem** [comment]
I opened it with another browser and this message appears.

"Address not understood.
Firefox does not know how to open this address, because the protocol (actionfps) is not associated with any program or is not allowed in this context.
You may need to install some application to open this address."

**Comment by BrutalSystem** [comment]
[I discovered why it was not working.](http://i.imgur.com/vi4BzHs.png?1)

I turned it off the first time.

**Comment by ScalaWilliam** [comment]
Thanks!
