### ISSUE TITLE
groupteams -> gather

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#28]
Replace groupteams with gather in the code. No need to change the logic. Just names. @ScalaWilliam found 'gather' was a better name for it.

**Comment by ScalaWilliam** [comment]
What do you think of the name? `/groupteams` might be easier for foreigners to understand than `/gather`

**Comment by lucasgautheron** [comment]
Groupteams

**Comment by ScalaWilliam** [comment]
thx
