### ISSUE TITLE
Map pick system

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#32]
* Requires team captains. 
 /captain cn team
 * /pickmap
If no captain: randomly picks one for each team
Size of initial map pool = 2n+1 (#29)
CS:GO style ? `Ban A - Ban B - Pick A - Pick B - Randomized 3rd map out of the three remaining`
First CLA has too choose (from a menu), then RVSF, then CLA etc.

**Comment by ScalaWilliam** [comment]
I think priority should be to finish #7 followed by an authentication system & a proper release system. All can be done in parallel.

**Comment by lucasgautheron** [comment]
@Sanzouille any help with the UX ? Something I haven't thought of

**Comment by Sanzouille** [comment]
idea: skip captain and assign a captain randomly

**Comment by lucasgautheron** [comment]
I want to keep the amount of votes as low as possible. Votes are slow and confusing.

**Comment by Sanzouille** [comment]
Also: when the captain is banning, he needs to ba bale to communicate via chat with his team

**Comment by ScalaWilliam** [comment]
Please, not for the first release. Let's not creep features in (and thus increase risk) until the essential bits are done.

**Comment by lucasgautheron** [comment]
It's not intended to be integrated into a first release
but very soon, at it's quite easy to implement and adds value

**Comment by ScalaWilliam** [comment]
What's the priority level for this? First release?

**Comment by ScalaWilliam** [comment]
postponing & medium priority.
