### ISSUE TITLE
User database generation and broadcast

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#33]
Design a system that generate and broadcast the users and groups databases under the right format to AC servers in order to allow users to authenticate. Should be done in real time upon registration or key-re generation. Need some UI @ actionfps.com
https://gist.github.com/Paul255/6c4dec4f13ef03f6579f

User DB format: text file with 1 line per used.
```
id=drakas name=w00p|Drakas group=woop group=UK pubkey=KEY
```
(where KEY is the based64 encoded public key)

Group DB format: text file with 1 line per used.
```
id=woop name=w00p
```

**Comment by ScalaWilliam** [comment]
Need to also think about how the private keys are issued. Are we still going with the 'assaultcube://' link approach?

**Comment by lucasgautheron** [comment]
Yes. Doesn't work on Linux because I don't know any consistent way to handle such custom protocols with across distributions & environments.
Otherwise, this could be done by downloading a file to the right place.

**Comment by ScalaWilliam** [comment]
Targeting Ubuntu should be enough.

**Comment by ScalaWilliam** [comment]
Ok to close?

https://github.com/ActionFPS/Incubator/blob/master/test_comb.py
