### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#34]
1. Build windows_client.exe
2. Run source/release/package_assaultcube.sh

Building windows_client.exe is the tricky part. Use windows VM ?

**Comment by ScalaWilliam** [comment]
Need a set of reproducible manual instructions first.

**Comment by lucasgautheron** [comment]
Some instructions are already available at https://github.com/lucasgautheron/ActionFPS-Game/wiki/Release

**Comment by ScalaWilliam** [comment]
Ok
`Run build scripts in source/vcpp/buildEnv/ on windows` is vague. How do you run them? which ones do you run? Why do you need multiple ones?

**Comment by lucasgautheron** [comment]
For historical reasons. I've updated them significantly but they are still split.
cd source/src/vcpp/buildEnv
start build_1_getfiles.bat
start build_2_prepare.bat
start build_3_makeinstaller.bat

**Comment by ScalaWilliam** [comment]
I was building it outside of a git repo:

```
cd source
cd vcpp
cd buildEnv
start build_1_getfiles.bat
```
First command gives me:
```
C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master\source\vcpp\buildEnv>mkdir ac

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master\source\vcpp\buildEnv>cd ../../..

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master>git archive -o source/vcpp/buildEnv/ac.zip HEAD
fatal: Not a git repository (or any of the parent directories): .git

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master>cd source/vcpp/buildEnv/ac/

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master\source\vcpp\buildEnv\ac>unzip.exe ../ac.zip
'unzip.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master\source\vcpp\buildEnv\ac>cd source/vcpp
The system cannot find the path specified.

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master\source\vcpp\buildEnv\ac>\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe cube.sln /p:Configuration=Release
Microsoft (R) Build Engine version 4.6.1038.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: cube.sln

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master\source\vcpp\buildEnv\ac>cd ../launcher
The system cannot find the path specified.

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master\source\vcpp\buildEnv\ac>\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe aclauncher.sln /p:Configuration=Release
Microsoft (R) Build Engine version 4.6.1038.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: aclauncher.sln

C:\Users\William\Downloads\ActionFPS-Game-master\ActionFPS-Game-master\source\vcpp\buildEnv\ac>pause
Press any key to continue . . .
```

**Comment by lucasgautheron** [comment]
Thanks for the logs.
I forgot to mention two things : 
 * Commands have to be executed inside of the git repository
 * unzip.exe is required (as provided in http://gnuwin32.sourceforge.net/packages/unzip.htm)

**Comment by ScalaWilliam** [comment]
doesn't seem to be downloadable from that site. isn't what you're doing with unzip + git a simple 'cp -R' for windows?

**Comment by lucasgautheron** [comment]
unzip.exe can be extracted from http://gnuwin32.sourceforge.net/downlinks/unzip-bin-zip.php linked in the aforementioned page.
'git archive' is called because it doesn't include untracked files or other files (.git/*), but it produces archives only (tar w/ or w/o or zip)
Maybe, if we do a fresh clone everytime before building, we could use cp instead (and remove .git files manually)

**Comment by ScalaWilliam** [comment]
nah, the git archive is enough. Could the compilation step be separated from the packaging completely?

**Comment by lucasgautheron** [comment]
Not sure what you mean (what for, and also if you are talking about
windows only or windows & linux)

How would it be an improvement ? And what do you mean, more practically
? I do not quite understand, sorry about that.

**Comment by ScalaWilliam** [comment]
The packaging requires extra software that compilation does not require, right? E.g. GIT, UNZIP, NSIS.

Typical procedure is to build the thing first, package later. :)

**Comment by DnC-f0r3v3r** [comment]
For compiling windows_client.exe, I think you could automate it in linux using MinGW. I am not sure about this, but if it could be made to work, I would think it would be much more efficient than trying to use Win VMs. I will look in to this and try to build it, but just a thought...

**Comment by lucasgautheron** [comment]
windows_client.exe is the installer, which requires NSIS (to be run on Windows, apparently there's no workaround). That's one step after compiling.
It's not too bad that we have to use a windows VM. If someone is experienced with this and can give it a try..

**Comment by ScalaWilliam** [comment]
Need an automated / reproducible command first, preferable without any use of GUI.
There's http://scoop.sh/ and https://chocolatey.org/

**Comment by ScalaWilliam** [comment]
Work is done:

https://github.com/ActionFPS/ActionFPS-Game/issues/48
