### ISSUE TITLE
Detect new versions

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#35]
Display a popup menu on game opening when a new version is available. Retrieve information from actionfps.com ?

**Comment by ScalaWilliam** [comment]
How about the masterserver? :)

**Comment by ScalaWilliam** [comment]
(could have a command like `echobig new version available`)

**Comment by lucasgautheron** [comment]
Something like this already exists
https://github.com/lucasgautheron/ActionFPS-Game/blob/master/source/src/client.cpp#L342
It's really not more complicated than fetching the list on startup, and having a menu to pop up if the AF is outdated.

**Comment by ScalaWilliam** [comment]
So what work is left there to make this work?

**Comment by lucasgautheron** [comment]
1. Add current_version xxx to the master server (https://actionfps.com/retrieve.do), where xxx is the latest version (as in https://github.com/lucasgautheron/ActionFPS-Game/blob/master/source/src/cube.h#L61)
 2. Fetch the server list silently on game start
 3. Display a menu automatically if AF is outdated

NB: I noticed the MS stopped working for some reasons. I suspect HTTPS. Unfortunately, the code base doesn't use cURL anymore which would made it very easy to allow for HTTPS served lists, but stef decided to use some home made http-get recipe instead...

**Comment by ScalaWilliam** [comment]
lol sounds like he had too much free time on his hands.
