### ISSUE TITLE
Make the game releasable on Ubuntu

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#36]
Two approaches:
1. Distribute a fully packaged DEB. Downloading a DEB and installing it is very easy and simple nowadays, I think for newbies would be much easier than figuring out how to use a .tar.bz2 file.
We cannot distribute this DEB to Ubuntu repositories due to media licensing restrictions, and for these there is another solution…

2. Distribute a media-free DEB. This could be uploaded to Ubuntu/Debian repositories. The client would download any missing textures and maps on start up.

Another advantage of doing *any* DEB release is we'd have a very consistent way of building and deploying the game packages. Take any Debian distribution, and it'll download all the source dependencies and stuff for us, and even perform the build - in one step. E.g.:
https://www.debian.org/doc/manuals/maint-guide/build.en.html#completebuild
```
$ dpkg-buildpackage -us -uc
```

**Comment by ScalaWilliam** [comment]
apt-get -y install debhelper dh-autoreconf

Looks like AssaultCube is already there in Ubuntu by default. Split into assaultcube and assaultcube-data packages:
https://launchpad.net/assaultcube

There's quite a bit of stuff involved to get it working so I will stick as far as the recently completed .tar.bz2 generation in #70.

Since it's already in Ubuntu repos, we may be able to sponge off (*depend* on ***sigh***) with packages from assaultcube-data package, meaning we just provide our own source packages and a smallish data package for any other package/map updates.

**Comment by lucasgautheron** [comment]
Just mentioning that there was already a script somewhere to upload a tar archive to github releases, some bits might still be helpful to this issue
https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/release/package_assaultcube.sh

**Comment by ScalaWilliam** [comment]
ahh had no idea. Thanks for pointing out.

**Comment by ScalaWilliam** [comment]
Should we bother with this?

Is .tar.bz2 enough for now perhaps?

I'm not keen on the whole packaging thing. There is a launchpad thing from which we could later integrate all the patches properly and THEN package an ubuntu.

**Comment by lucasgautheron** [comment]
tar.bz2 enough for now imo.

**Comment by ScalaWilliam** [comment]
Postponing.
