### ISSUE TITLE
Remove home-made HTTP library

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#37]
So that we are more flexible with HTTP usage.

- [ ] Re-integrate libcurl support for windows, debian-based systems, and mac
- [ ] Remove httpget.cpp (abomination)
- [ ] Write some interface with multi thread support instead
- [ ] Update the serverbrowser
- [ ] Remove the auto-download feature ? to be replaced with #39

**Comment by lucasgautheron** [comment]
:+1:

**Comment by ScalaWilliam** [comment]
I can descope this as might not be essential for release.

**Comment by lucasgautheron** [comment]
Still need to figure out what's wrong with #78
The MS should now accept http requests right ?

**Comment by ScalaWilliam** [comment]
Now it should work:
https://github.com/ScalaWilliam/ActionFPS/issues/204#issuecomment-276227809

**Comment by ScalaWilliam** [comment]
Won't happen in first release, so postponing.
