### ISSUE TITLE
Key generation process

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#38]
![Diagram](https://docs.google.com/drawings/d/1skIW9U8jB-sk-U7y-M3OJVrgCRUOh1NJnDdWzC6BiEE/pub?w=443&h=254)

**Comment by ScalaWilliam** [comment]
Server's database update procedure:
'scp data.db server:/path/to/af/server/'

af server notices the file that was changed just now, reloads it.
Must account for race condition which loads the file partially. I'd say just make sure that the file size has not changed in the next 1 second & then reload it fully.

**Comment by ScalaWilliam** [comment]
Actually inotify can give us that for free:
http://man7.org/linux/man-pages/man7/inotify.7.html

So for the server, if on Windows, no auto-reload, if on Linux, then auto-reload with inotify's `IN_CLOSE_WRITE` event! 💯
