### ISSUE TITLE
Proposal for ActionFPS-Game-Media repository aka Akimbo-on-GitHub

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#39]
From discussion over at ActionFPS: https://github.com/ScalaWilliam/ActionFPS/issues/238#issuecomment-271849757

**Summary**: separate media from code, automate *everything* and create an intersection between Akimbo and GitHub workflow.

One strength of AC was that we had Akimbo, which allowed people to submit Media content, such as:
* Maps
* Mods
* Scripts
* Skymaps
* Textures
* Mapmodels

Weaknesses were:
1. Media would still be difficult to fetch and integrate into the game: you'd have to be actively involved to find this new content.
2. Reviewing the content is difficult, eg ensuring standards such as displayed here: [Submit Content, Files Packaging and Auto-Download
](http://web.archive.org/web/20160414182544/http://ac-akimbo.net/showthread.php?tid=30)
3. [Maintaining download servers](http://web.archive.org/web/20131122170244/http://ac-akimbo.net/showthread.php?tid=149)
4. Another weakness for ActionFPS is that the game currently distributes licensed media and there are licensing concerns if we wanted to for example push ActionFPS to an Ubuntu repository. While the source code is FOSS the media is not and thus cannot package it together at all.

My proposal is:
1. Move all the media to a new repository, ActionFPS-Game-Media.
2. Create an 'incubating' directory for all the incubating maps, stuff that is being tested etc.
3. Have an 'official' directory for all the stuff everyone would download.
4. Automatically build releases and publish as GitHub Releases (whether for all stuff combined or separately)
5. Automatically download from 'official' (or 'incubating', if option enabled) repository on game launch and synchronise when possible.
6. Use 'incubating' as target and example where people can put their Pull Requests into. Pull requests would contain map and media updates that everybody can review. Quality standards must all pass properly and the checking can be automatically done in something like Travis-CI for each commit in the pull requests.
7. Use 'issues' as a forum for questions.
8. If an author of a Media does not want their content hosted and packaged together with other content, we can always replace the content itself with links to other hosted targets.
9. Pull requests: for map submissions we could automatically render and post a map's view for easy evaluation. Lots of automation potential right here.
10. Akimbo-ac website can be made into a static page which serves as a central index of all the content (screenshots, map layouts automatically generated and published) with credits where due. Maps can have JSON/YML files attached to them with author info, we can credit authors much more easily, provide them with various links.
11. Stuff in 'incubating' moves to 'official' when we decide to.
12. We can begin removing many maps and media from our distro. Alternatively,
13. We can download AssaultCube media as a separate resource and then put stuff on top via ActionFPS-Game-Media. This way, we start with a fresh repository in a way. That repository can contain only the instructions of how to get stuff (see point #8) for the client.

**Comment by ScalaWilliam** [comment]
I'm happy to contribute to the automation. akimbo-ac site ofc gets generated automatically too :)

**Comment by lucasgautheron** [comment]
Excellent! Then I'd opt for dropping autodownload (in its current state) completely.
And synchronizing would be all about finding an efficient way to compare releases to local media.

**Comment by ScalaWilliam** [comment]
Let me create a set of tickets for this then.

**Comment by ScalaWilliam** [comment]
## ActionFPS-Game 
* [ ] Game: download official AssaultCube Media as a .ZIP so we don't host any of it and deal with packaging issues.
* [ ] Game: Extract AssaultCube media in an appropriate directory for the download to work. Will require ignoring some files.
* [ ] Support the resource description format of ActionFPS-Game-Media


## ActionFPS-Game-Media
* [ ] Create some sort of mapping between an externally hosted content and automate that in publishing a resource file tree or something. Download instructions so to speak. They should be declarative.
* [ ] Move AF-specific content to ActionFPS-Game-Media
* [ ] Create an 'incubating' directory
* [ ] Create an 'official' directory
* [ ] Script to ZIP 'official' automatically
* [ ] Travis integration to publish release ZIP automatically on tag.
* [ ] Automatic download of release ZIP for the game
* [ ] Implement some basic quality standards for pull requests (eg each package must have a meta file of some sort and/or a Makefile)
* [ ] Document 'incubating' and 'official' in the Wiki. Document purpose of 'issues' and 'pull requests'.
* [ ] Make reference to 'Wiki', 'incubating' and 'official' from README.md
* [ ] Render a map's image automatically and attach it to a pull request
* [ ] Remove unnecessary maps from the distribution

**Comment by ScalaWilliam** [comment]
Not important ATM, will close.
