### ISSUE TITLE
Lua + C > CubeScript + C

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#41]
Benefits:
* Flexible common language
* Ability to replace lots of existing C code with Lua 
* Attract more game developers
* Increased testability

We could reduce the code size massively by rewriting both C and CubeScript into Lua, removing the CubeScript implementation.

Lua is popular with game scripting and configuration so this could potentially open up a lot more doors to user contribution.

With Lua it'll be possible to introduce proper Unit Testing for many parts of the code (eg server logic) and also reimplement server logic in Lua too.
* http://lua-users.org/wiki/UnitTesting
* https://olivinelabs.com/busted/
* https://www.gamedev.net/resources/_/technical/game-programming/the-lua-tutorial-r2999
* https://www.lua.org/gems/
* https://en.wikipedia.org/wiki/Category%3aLua-scripted_video_games

**Comment by ScalaWilliam** [comment]
Not important rn.

**Comment by lucasgautheron** [comment]
https://github.com/gear4s/aclua-1.2 < Lua mod for assaultcube
