### ISSUE TITLE
Make automated build on Windows work (AppVeyor)

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#43]

**Comment by ScalaWilliam** [comment]
https://ci.appveyor.com/project/ScalaWilliam/actionfps-game/build/1.0.1

**Comment by ScalaWilliam** [comment]
https://ci.appveyor.com/project/ScalaWilliam/actionfps-game/build/1.0.4

**Comment by ScalaWilliam** [comment]
http://www.hanselman.com/blog/AppVeyorAGoodContinuousIntegrationSystemIsAJoyToBehold.aspx

**Comment by lucasgautheron** [comment]
Nice! Will do that. And fix the issue with openssl.
