### ISSUE TITLE
TOSOK to count score by round

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#44]
Total score of tosok could be number of rounds won - would make a big difference ;)

**Comment by lucasgautheron** [comment]
Agreed

**Comment by lucasgautheron** [comment]
This requires team scores to be saved somewhere; In AC, team scores are calculated as the sum of individual scores, but this does not permit such a system.

**Comment by ScalaWilliam** [comment]
Maybe let's not worry about this for now. Bigger fish to fry. Feel free to close Issue.

**Comment by ScalaWilliam** [comment]
Not important rn.
