### ISSUE TITLE
private server autoteam to be off always

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#46]
annoying it just changes the teams in the middle of the game

**Comment by lucasgautheron** [comment]
@ScalaWilliam 
what do you mean by private server ?
 * mastermode == private or match ?
 * or should autoteam be off, always, for some servers (i.e. make a server switch for that)

**Comment by ScalaWilliam** [comment]
autoteam for game == match || server config option set.

**Comment by lucasgautheron** [comment]
https://github.com/ActionFPS/ActionFPS-Game/commit/78b36b0dffa873cb89e28682afc11cbb7b558cfc
