### ISSUE TITLE
build_2_prepare.bat broken

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#49]
https://github.com/ActionFPS/ActionFPS-Game/blob/1bad3d815880fc1f4663b05d33cc6e0eaca4e069/source/vcpp/buildEnv/build_2_prepare.bat#L31
e.g. no `packages\models\misc\gib02\shadows.dat` as specified here exists:
https://github.com/ActionFPS/ActionFPS-Game/tree/1bad3d815880fc1f4663b05d33cc6e0eaca4e069/packages/models/misc/gib02

**Comment by lucasgautheron** [comment]
shadows.dat files are precalculated data used while rendering 3d models
if they do not exist, then the game generates them.
so there are two solutions:
 * Run the game once to generate all of them.
 * Do not release them any longer and let the client generate them at first game start.

I'd suggest the second option.

**Comment by ScalaWilliam** [comment]
How is the second option doable?

**Comment by ScalaWilliam** [comment]
Thx.
