### ISSUE TITLE
Discord notifications for this GitHub repo

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#50]

**Comment by Sanzouille** [comment]
Will do

**Comment by lucasgautheron** [comment]
@Sanzouille is it working?

**Comment by Sanzouille** [comment]
seems like, will see when next commits are done i guess

**Comment by ScalaWilliam** [comment]
Confirmed working.
<img width="334" alt="screen shot 2017-01-28 at 23 09 54" src="https://cloud.githubusercontent.com/assets/2464813/22397555/e65c9a00-e5ae-11e6-98b6-8eca63b79870.png">

Thx Sanzo.
