### ISSUE TITLE
build_3_makeinstaller.bat won't work

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#51]
![image](https://cloud.githubusercontent.com/assets/2464813/22329204/2db6e0c8-e3fb-11e6-9e9d-49421955b4fa.png)

    Plugin not found, cannot call GetVersion::WindowsVersion
    Error in script "af.nsi" on line 492 -- aborting creation process

Latest NSIS 3 (tried 2 too, same error)

**Comment by lucasgautheron** [comment]
More luck with #53 ?
