### ISSUE TITLE
Version number unification

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#56]
Should make version number easy to set and make consistent across all packages
https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/release/package_assaultcube.sh#L136

Currently too complicated: https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/release/package_assaultcube.sh#L136

What's the best way to handle that ?

**Comment by ScalaWilliam** [comment]
Best way is to get it from the git tag.

**Comment by ScalaWilliam** [comment]
There's <a href="https://git-scm.com/docs/git-describe">`git describe`</a>.

**Comment by lucasgautheron** [comment]
The source code also include the version number in many locations
under very different format
 * https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/src/cube.h#L61 > integer, e.g. 1200
 * https://github.com/ActionFPS/ActionFPS-Game/blob/master/actionfps_release.bat v"major.minor"
 * sometimes the full version

**Comment by ScalaWilliam** [comment]
Any serious use of the version in sources actually is use of protocol version number to verify compatibility between client and server.
For the time being I think the protocol version number should stay as is - but in the longer run, modularity would help get rid of the protocol version and instead compatibility is defined by the code itself - ie automated testing between different client-server versions, test reports, etc.

As for user configuration, depends whether it's backwards compatible or not too. Ideally we import settings from a previous installation, and copy into a new installation. But this is a lot of painful work. Might be much more fun to minimise customisation and get people to contribute their mods/customisations into the mainline instead :grin:.

Non-code versions should be pulled in via git tag, eg. `git describe`.

**Comment by lucasgautheron** [comment]
> Any serious use of the version in sources actually is use of protocol version number to verify compatibility between client and server.
There are two things, AF_VERSION which is used to detect updates, and PROTOCOL_VERSION to reject clients or demos

**Comment by ScalaWilliam** [comment]
Updates could be tied to the git tag/whatever. A basic check if mine != released, which can be any arbitrary string.

**Comment by ScalaWilliam** [comment]
If we had curl then we'd get:
https://raw.githubusercontent.com/ActionFPS/ActionFPS-Game/master/LATEST_VERSION
or something (that even could contain motd and stuff!)

Acting a bit like a master server.

Here you can get README.md for example, in raw form, very easily.
https://raw.githubusercontent.com/ActionFPS/ActionFPS-Game/master/README.md
