### ISSUE TITLE
Authentication URL format? Or users db format

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#58]
Not sure what it is, something ain't matching.

**Comment by lucasgautheron** [comment]
https://github.com/ActionFPS/ActionFPS-Game/blob/5f601185273b4ed00c0cb9e86151382ad540528a/source/src/main.cpp#L1017

**Comment by lucasgautheron** [comment]
So:
actionfps://key=...&id=...

**Comment by ScalaWilliam** [comment]
Can you give an example URL? The code is too confusing, eg I'm not sure if I require to put in a server.

I didn't have time to make sure it's quality ;)

**Comment by lucasgautheron** [comment]
check my edit :)

**Comment by ScalaWilliam** [comment]
maybe a full working url :+1: ?

**Comment by ScalaWilliam** [comment]
I should be done for the night, cause this has been some intense work ;) brain not working so well no more.

**Comment by lucasgautheron** [comment]
Sure :)

**Comment by ScalaWilliam** [comment]
auth url still bugged. Will open a separate ticket for it.

**Comment by ScalaWilliam** [comment]
#80.
