### ISSUE TITLE
ActionFPS Blog WordPress

### ISSUE THREAD

**Issue by DaylixX** [ActionFPS/ActionFPS-Game#63]
- What do you need on the Blog ?
- Let's use it over the long term ?
-  We use it just for #tournaments or more ?

**Comment by DaylixX** [comment]
I have added a connection to join our discord on the menu

**Comment by lucasgautheron** [comment]
This belongs to ScalaWilliam/ActionFPS ;)

**Comment by DaylixX** [comment]
How i change it ?

**Comment by ScalaWilliam** [comment]
copy&paste really :)

**Comment by DaylixX** [comment]
Wrong Project
