### ISSUE TITLE
Circle -> travis?

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#66]
Noticed this change here:
https://github.com/ActionFPS/ActionFPS-Game/commit/00e61f42f2243abe49d5c536f9541059a8e2b97f

What's the reason for it?

**Comment by lucasgautheron** [comment]
Circle was first chosen because this repository was private, and travis has no free plan for private repository support. But I felt more comfortable with travis.
If travis is not as good, then we can drop it if necessary.

**Comment by ScalaWilliam** [comment]
We're using Travis for Linux, Circle for OS X, AppVeyor for Windows. The combination is fine and working so no need to change it. Thanks for clarifying.
