### ISSUE TITLE
OS X Build to run

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#81]
As it doesn't run right now.

Following up from #45.

**Comment by ScalaWilliam** [comment]
<img width="391" alt="screen shot 2017-01-31 at 20 50 40" src="https://cloud.githubusercontent.com/assets/2464813/22465491/f514f16a-e7f6-11e6-925a-681b657143ef.png">

command: `open 'assaultcube://authenticat...'`

On another user account it just plain crashes...

**Comment by lucasgautheron** [comment]
assaultcube:// ? Why not actionfps:// ?
Also, do you know if assaultcube:// links are handled by vanilla AssaultCube on Mac, so we know better where the problem might be lying?

**Comment by ScalaWilliam** [comment]
because I didn't change it to actionfps:// yet.

assaultcube:// works on mac just fine.

**Comment by ScalaWilliam** [comment]
Verified runs in normal flow.
