### ISSUE TITLE
Verify windows auth full stack works

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#82]
so we can develop more easily? and also achieve #48.

**Comment by ScalaWilliam** [comment]
`sudo apt-get -y install playonlinux`

**Comment by lucasgautheron** [comment]
Just tested the game on playonlinux, but not authentication. It worked.
Testing authentication "full chain" is trickier because of browser should be run through the same wine environment or something I guess.

**Comment by ScalaWilliam** [comment]
The auth itself works but the link doesn't 359 characters instead of 680 characters are loaded in by actionfps client into 'authkey'.

**Comment by lucasgautheron** [comment]
Fix attempt in https://github.com/ActionFPS/ActionFPS-Game/commit/2c4a0f713e7519f204566d4b4d2ca2ac0f1ffd77

**Comment by ScalaWilliam** [comment]
2c4a0f713e7519f204566d4b4d2ca2ac0f1ffd77 fixes

**Comment by ScalaWilliam** [comment]
& works for me ofc.
