### ISSUE TITLE
remove all instances of http://assault.cubers.net/ from code

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#83]
eg when we install the game, it takes us to 'http://assault.cubers.net/releasenotes/v1.2/' in the browser, which we don't want.

we may also need to remove a lot of docs ;)

**Comment by lucasgautheron** [comment]
Can we still have release notes somewhere?

**Comment by ScalaWilliam** [comment]
Yes we'll use either Git or GitHub Releases for that.
