### ISSUE TITLE
Proper README.md and INSTALL.md

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#89]
* Remove redundant stuff
 * Make it nice and exhaustive

**Comment by ScalaWilliam** [comment]
Until we sign the code, users will need to do this:
https://successfulsoftware.net/2012/08/30/how-to-sign-your-mac-os-x-app-for-gatekeeper/

**Comment by ScalaWilliam** [comment]
This for CircleCI: https://circleci.com/docs/ios-code-signing/

**Comment by ScalaWilliam** [comment]
I'll add it to first release, as I think it's important to be well documented.

**Comment by ScalaWilliam** [comment]
It's actually in the <a href="https://actionfps.com/play/">ActionFPS Play</a> page, I'm happy to close this. @lucasgautheron ?

**Comment by ScalaWilliam** [comment]
Closing, as it's good enough to me. README does build-only. INSTALL is on AF website.
So no redundant info (important)
