### ISSUE TITLE
Team size 

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#9]
Make sure team size is calculated and outputted in logs

> Team size is a variable managed by AC servers which define how many players are "active". It is useful for autopause, and to prevent spectators from spawning (if the amount of active players is already >= 2*teamsize)
> In AC, the variable is here, but unused/not properly implemented. This issue is about fixing it.

**Comment by ScalaWilliam** [comment]
Postponing.

**Comment by lucasgautheron** [comment]
This is important:/ flow breaking stuff. E.g let you spawn on the fullest team etc

**Comment by ScalaWilliam** [comment]
Essential for the first release?

**Comment by lucasgautheron** [comment]
Yes. Not so hard to just remove if we want
