### ISSUE TITLE
codeblocks -> eclipse

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#92]
Include eclipse project rather than codeblocks. Code::blocks is deprecated, and keeps crashing on my linux.

**Comment by ScalaWilliam** [comment]
I like this. Eclipse seems to be cross platform. There's also CLang, or just take a look at my tweet here: https://www.quora.com/What-is-the-best-C-C%2B%2B-IDE?srid=DB6V

**Comment by ScalaWilliam** [comment]
Low priority but would be very nice. I'll put in postponed, pick up when you like.
