### ISSUE TITLE
groups not working properly

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#96]
Expected behavior:
 * ```/group woop``` should set default group to 'woop', offline or online, with immediate effect if online
 * w00p should appear in the group column as a result

I got it working only once. Need to investigate this ASAP.

**Comment by ScalaWilliam** [comment]
I only expect it to work online, because offline the client just doesn't have the information - and the client won't have this information, either.

**Comment by lucasgautheron** [comment]
of course it is only supposed to "work" online, but you should be able to switch your default group offline
remember a user can switch to many groups
